version: "2"
linters:
  enable:
    - bodyclose
    - gocritic
    - gosec
    - makezero
    - nestif
    - nilerr
    - noctx
    - unparam
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: .go
        text: .*could not import*
      - path: (.+)\.go$
        text: Using the variable on range scope .* in function literal
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
