package remnant

const (
	LGHuntingRifle        = "HuntingRifle"
	LGCoachGun            = "CoachGun"
	LGShotgun             = "Shotgun"
	LGAssaultRifle        = "AssaultRifle"
	LGBeamRifle           = "BeamRifle"
	LGDevastator          = "Devastator"
	LGSniperRifle         = "SniperRifle"
	LGSporebloom          = "Sporebloom"
	LGCrossbow            = "Crossbow"
	LGRuin                = "Ruin"
	LGEyeoftheStorm       = "EyeoftheStorm"
	LGParticleAccelerator = "ParticleAccelerator"
	LGRepulsor            = "Repulsor"
	LGRicochetRifle       = "RicochetRifle"
	LGChicagoTypewriter   = "ChicagoTypewriter"
	LGAlternator          = "Alternator"
	LGFusionRifle         = "FusionRifle"
)

const (
	HGRepeaterPistol      = "RepeaterPistol"
	HGMagnumRevolver      = "MagnumRevolver"
	HGDefiler             = "Defiler"
	HGHuntingPistol       = "HuntingPistol"
	HGSubmachineGun       = "SubmachineGun"
	HGHiveCannon          = "HiveCannon"
	HGSpitfire            = "Spitfire"
	HGCurseoftheJungleGod = "CurseoftheJungleGod"
	HGPrideoftheIskal     = "PrideoftheIskal"
	HGMachinePistol       = "MachinePistol"
	HGSawedOff            = "Sawed-Off"
	HGTwinShot            = "TwinShot"
)

const (
	MWScrapSword         = "ScrapSword"
	MWScrapHammer        = "ScrapHammer"
	MWScrapHatchet       = "ScrapHatchet"
	MWBladeofAdventure   = "BladeofAdventure"
	MWPetrifiedMaul      = "PetrifiedMaul"
	MWWastelanderFlail   = "WastelanderFlail"
	MWScythe             = "Scythe"
	MWWorldBreaker       = "WorldBreaker"
	MWSpear              = "Spear"
	MWScarofTheJungleGod = "ScarofTheJungleGod"
	MWSmolder            = "Smolder"
	MWVoiceofTheTempest  = "VoiceofTheTempest"
	MWButchersFlail      = "ButchersFlail"
	MWGuardianAxe        = "GuardianAxe"
	MWLostHarpoon        = "LostHarpoon"
	MWRiven              = "Riven"
	MWHerosSword         = "Hero'sSword"
	MWFrostborne         = "Frostborne"
	MWChainBlade         = "ChainBlade"
	MWWorldsEdge         = "World'sEdge"
)

const (
	ArmAdventurer = "Adventurer"
	ArmAkari      = "Akari"
	ArmBandit     = "Bandit"
	ArmBomber     = "Bomber"
	ArmCarapace   = "Carapace"
	ArmCultists   = "Cultist's"
	ArmDrifters   = "Drifter's"
	ArmElder      = "Elder"
	ArmHunter     = "Hunter"
	ArmLabyrinth  = "Labyrinth"
	ArmLetos      = "Leto's"
	ArmOsseous    = "Osseous"
	ArmRadiant    = "Radiant"
	ArmScavengers = "Scavenger's"
	ArmScrapper   = "Scrapper"
	ArmSlayer     = "Slayer"
	ArmTwisted    = "Twisted"
	ArmVoid       = "Void"
	AWarlords     = "Warlord's"
)

const (
	RAggressorsBane       = "Aggressor's Bane"
	RAkariWarBand         = "Akari War Band"
	RAlchemistsJewel      = "Alchemist's Jewel"
	RAmberMoonstone       = "Amber Moonstone"
	RBackbreakerRing      = "Backbreaker Ring"
	RBandofAccord         = "Band of Accord"
	RBandofCastor         = "Band of Castor"
	RBandofDiscord        = "Band of Discord"
	RBandofPollux         = "Band of Pollux"
	RBandofStrength       = "Band of Strength"
	RBlackCatBand         = "Black Cat Band"
	RBloodFont            = "Blood Font"
	RBloodlettersInsignia = "Bloodletter's Insignia"
	RBraidedThorns        = "Braided Thorns"
	RBrightSteelRing      = "Bright Steel Ring"
	RBurdenoftheDevoted   = "Burden of the Devoted"
	RBurdenoftheFollower  = "Burden of the Follower"
	RBurdenoftheGambler   = "Burden of the Gambler"
	RBurdenoftheReckless  = "Burden of the Reckless"
	RBurdenoftheWarlord   = "Burden of the Warlord"
	RCelerityStone        = "Celerity Stone"
	RCompulsionLoop       = "Compulsion Loop"
	RDeceiversBand        = "Deceiver's Band"
	RDevouringLoop        = "Devouring Loop"
	REmpoweringLoop       = "Empowering Loop"
	REvokersSeal          = "Evoker's Seal"
	REzlansBand           = "Ezlan's Band"
	RFiveFingeredRing     = "Five Fingered Ring"
	RGiftoftheIskal       = "Gift of the Iskal"
	RGravityStone         = "Gravity Stone"
	RGrimCoil             = "Grim Coil"
	RGuardiansRing        = "Guardian's Ring"
	RGunslingersRing      = "Gunslinger's Ring"
	RHeartoftheWolf       = "Heart of the Wolf"
	RHeartseeker          = "Heartseeker"
	RHerosRing            = "Hero's Ring"
	RHuntersBand          = "Hunter's Band"
	RHuntersHalo          = "Hunter's Halo"
	RIskalHunterBand      = "Iskal Hunter Band"
	RoftheBlackSun        = "of the Black Sun"
	RJuggernautBand       = "Juggernaut Band"
	RKeepersRing          = "Keeper's Ring"
	RLeechEmber           = "Leech Ember"
	RLoopofProsperity     = "Loop of Prosperity"
	RMothersRing          = "Mother's Ring"
	RPearlofLuminescence  = "Pearl of Luminescence"
	RPillarofStone        = "Pillar of Stone"
	RPrismaticDiamondRing = "Prismatic Diamond Ring"
	RProvisionerRing      = "Provisioner Ring"
	RRazorstone           = "Razorstone"
	RRestrictionCord      = "Restriction Cord"
	RRingofElusion        = "Ring of Elusion"
	RRingofEvasion        = "Ring of Evasion"
	RRingofFlawlessBeauty = "Ring of Flawless Beauty"
	RRingofHonor          = "Ring of Honor"
	RRingofShadows        = "Ring of Shadows"
	RRingofSupremacy      = "Ring of Supremacy"
	RRingofSynergy        = "Ring of Synergy"
	RRingoftheAdmiral     = "Ring of the Admiral"
	RRingoftheMantis      = "Ring of the Mantis"
	RRingofthePunisher    = "Ring of the Punisher"
	RRingoftheUnclean     = "Ring of the Unclean"
	RRootCirclet          = "Root Circlet"
	RSagestone            = "Sagestone"
	RScavengersRing       = "Scavenger's Ring"
	RSerpentsFang         = "Serpent's Fang"
	RSoulEmber            = "Soul Ember"
	RSoulLink             = "Soul Link"
	RSpiritStone          = "Spirit Stone"
	RStockpileCirclet     = "Stockpile Circlet"
	RStoneOfBalance       = "Stone Of Balance"
	RSwashbucklersSignet  = "Swashbuckler's Signet"
	RVanguardRing         = "Vanguard Ring"
	RVolatileGem          = "Volatile Gem"
)

const (
	AmuAbrasiveAmulet            = "Abrasive Amulet"
	AmuAmuletofEpicaricacy       = "Amulet of Epicaricacy"
	AmuBlackRose                 = "Black Rose"
	AmuBlessedNecklace           = "Blessed Necklace"
	AmuBrutalMark                = "Brutal Mark"
	AmuButchersFetish            = "Butcher's Fetish"
	AmuCharcoalNecklace          = "Charcoal Necklace"
	AmuCleansingJewel            = "Cleansing Jewel"
	AmuDaredevilsCharm           = "Daredevil's Charm"
	AmuDriftstone                = "Driftstone"
	AmuGalenicCharm              = "Galenic Charm"
	AmuGunslingersCharm          = "Gunslinger's Charm"
	AmuHangmansMemento           = "Hangman's Memento"
	AmuHeartofDarkness           = "Heart of Darkness"
	AmuLetosAmulet               = "Leto's Amulet"
	AmuMendersCharm              = "Mender's Charm"
	AmuNightmareSpiral           = "Nightmare Spiral"
	AmuOnyxPendulum              = "Onyx Pendulum"
	AmuPocketWatch               = "Pocket Watch"
	AmuPolishedWhetstone         = "Polished Whetstone"
	AmuRadioactiveEmber          = "Radioactive Ember"
	AmuRazorwireNecklace         = "Razorwire Necklace"
	AmuRockofAnguish             = "Rock of Anguish"
	AmuRustedAmulet              = "Rusted Amulet"
	AmuScavengersBauble          = "Scavenger's Bauble"
	AmuShatteredVertebrae        = "Shattered Vertebrae"
	AmuSoulAnchor                = "Soul Anchor"
	AmuStalkersBrand             = "Stalker's Brand"
	AmuStormAmulet               = "Storm Amulet"
	AmuTalismanOfAnimosity       = "Talisman of Animosity"
	AmuTalismanofPerseverance    = "Talisman of Perseverance"
	AmuTerrorMargin              = "Terror Margin"
	AmuTwistedIdol               = "Twisted Idol"
	AmuVengeanceIdol             = "Vengeance Idol"
	AmuVulcansDetonatorWhiteRose = "Vulcan's DetonatorWhite Rose"
)
